spring:
  application:
    name: lanuz
  profiles:
    active: dev # Env variable's default value syntax
#Configuracion para archivos
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
media:
  location: mediafiles


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      CategoriaNombreUnique: CATEGORIA_NOMBRE_UNIQUE
      ProductoCodigoUnique: PRODUCTO_CODIGO_UNIQUE

---
### DESARROLLO ###
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/pos-api?serverTimezone=UTC
    username: root
    password:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

---

### PRODUCCION ###
spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

---